### PR TITLE
Part 2 Balsamiq with animated gif pause and play

### PR DESCRIPTION
**Pull request by annegentle**
Here's part 2, ready to go next week. I changed quite a bit of the wording to get the series to flow and not repeat the background exactly. Probably making it difficult to revise again for the third, but I'd like these each to standalone. Take a look and let me know if it's good,  @balsamiqLeon -- I'll post early next week once it's good-to-go.

Here's a screenshot -

screencap-balsamiq-part2

### CODE REVIEW

**Comment by balsamiqLeon** [comment]
Hi @annegentle, it looks great! The only thing I'd add is maybe a link to the first post in the first sentence after the second heading so it makes a little more sense.
Something like:
"In a very different challenge from our [first one](http://docslikecode.com/articles/balsamiq-case-study-part-1/), we noticed..."

**Comment by annegentle** [comment]
Thanks Leon! I'll get this published this morning. Dance, banana, dance.

**Comment by annegentle** [comment]
Ha, I committed the classic mistake and forgot to `git add` the article. Working on it now.

**Comment by annegentle** [comment]
@balsamiqLeon I'll shipit :shipit: today -- thanks for the review!

**Comment by balsamiqLeon** [comment]
Woo-hoo, looks great!

**Pull request merged**
